# Dependabot ouvre une pull request quand une action utilisée par la CI sort en nouvelle version
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "CI"
